
import { Weight } from "lucide-react";
import "./globals.css";
import { Assistant } from "next/font/google";
import { ToastContainer } from "react-toastify";
import GlobalStoreProvider from "@/components/Application/GlobalStoreProvider";
const assistantFont = Assistant({
  Weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${assistantFont.className} antialiased`}
      >
        <GlobalStoreProvider> 
         <ToastContainer />
        {children}

        </GlobalStoreProvider>
       
      </body>
    </html>
  );
}
